"""Common backend contract for simulation and real robots."""
from typing import Protocol

class RobotBackend(Protocol):
    def move_joint(self, positions: dict, duration_ms: int, lease) -> None: ...
    def pick_object(self, target_id: str, grasp_pose: dict, duration_ms: int, lease) -> dict: ...
    def stop(self, lease) -> None: ...
    def step(self, count: int = 1) -> dict: ...

    # 可视化与生命周期契约：供 Viewer 等显示入口调用，内部自行加锁，
    # 调用方不得直接访问实现的下划线私有成员。
    def start_continuous(self) -> bool: ...
    def stop_continuous(self, timeout: float = 2.0) -> bool: ...
    def is_continuous(self) -> bool: ...
    def render_frames(self, count: int = 1) -> list: ...
    def home_pose(self) -> dict: ...
    def hold_current_pose(self) -> dict: ...
    def simulation_status(self) -> dict: ...
    # 显示同步互斥：Viewer 同步会复制 mjData，必须与物理步进互斥，
    # 否则 MuJoCo 报 "copy mjData while stack is in use"。
    # 调用方以 with backend.display_lock(): viewer.sync() 的方式使用。
    def display_lock(self): ...
